### ISSUE TITLE
PPT中不理解的地方

### ISSUE THREAD

**Issue by fanhualu** [imtaotao/co-share#1]
// 问题在于异步请求是副作用，我们无法预测这个结果在什么时间到来
// 导致我们无法保证程序的顺序。同样也很难复现，同样的输入可能导致不同的输出
      async getMessage () {
        this.message = await fetch('xx')
      }

为什么说这边会有bug呢？能否解释下啊

**Comment by imtaotao** [comment]
js 是单线程的，如果同步执行代码，那么整个逻辑是从上往下，整个逻辑是可控的，但是如果其中掺杂有异步任务等不可预测的行为。那么整个逻辑就是不可控的，你无法预测在这段异步任务会对你现有的逻辑造成什么影响。

比如这里，调用 getMessage 方法，可能的就是前发的请求在后面到来，这样也就是说，旧的数据会覆盖新的数据渲染上去。
