### ISSUE TITLE
amazing！PPT动画和内容都做的很惊艳呀，有相关的参考资料吗？下次团队分享也搞一波

### ISSUE THREAD

**Issue by mrrs878** [imtaotao/co-share#2]

**Comment by imtaotao** [comment]
这个有点困难，模块加载器和框架都是自己写的，应该不太适用，不过你用 vue 或者 react 写都没问题。ppt 用的是 impress.js，代码高亮用的是 highlight.js

内容没有啥资料，都是前两年学习的积累

**Comment by mrrs878** [comment]
好的，感谢回复
